⚡Added CodeBlockParser
KrishAgarwal2811/djs-utility pull request #9
Opened 2021-09-18 15:40 UTC by RajnishAnand

⚡added Readme
⚡add in test-bot
⚡updated package-lock.json
⚡Added my bot token 😂 kidding

2021-09-21 10:23 UTC, KrishAgarwal2811 requested changes

2021-09-21 10:23 UTC, KrishAgarwal2811 commented on README.md
> -# Contributing
You removed this heading but never added it again :chadthink:

2021-09-21 10:23 UTC, KrishAgarwal2811 commented on README.md
> +> Exemple :
typo

2021-09-21 17:04 UTC, RajnishAnand commented on README.md
> -# Contributing
:chadthink: i don't remember tho 😅

2021-10-01 09:20 UTC, KrishAgarwal2811 requested changes

2021-10-01 09:20 UTC, KrishAgarwal2811 commented on README.md
> -# Contributing
no it isn't there :chadthink:

2021-10-01 09:55 UTC, RajnishAnand commented
fixed now 😅 `# contribution` added
and typo : `Exemple` →`Example` phixed

2021-10-01 13:23 UTC, merged